---
title: "HW2-Test"
output: html_document
date: "2024-09-22"
---

```{r}
library(tidyverse)

move_fri <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Movement Data/park-movement-Fri.csv") |>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")

move_sat <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Movement Data/park-movement-Sat.csv") |>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")



move_sun <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Movement Data/park-movement-Sun.csv") |>
  filter(id != "id") |>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")

comm_fri <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Communication Data/comm-data-Fri.csv")|>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")

comm_sat <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Communication Data/comm-data-Sat.csv")|>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")
comm_sun <- read_csv("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Communication Data/comm-data-Sun.csv")|>
  separate("Timestamp", into=c("date", "time"), sep = " ") |>
  separate("date", into=c("year", "month", "day"), sep = "-") |>
  separate("time", into=c("hour", "min", "sec"), sep = ":")


move_sun$id <- as.numeric(move_sun$id)
```





Joining to figure out main rides
```{r}
joint_fri <- move_fri |>
  filter(type == "check-in") |>
  inner_join(comm_fri, by = c("id" = "from", "day" = "day", "hour" = "hour", "min" = "min", "sec" = "sec")) |>
  distinct(X, Y, location)

joint_sat <- move_sat |>
  filter(type == "check-in") |>
  inner_join(comm_sat, by = c("id" = "from", "day" = "day", "hour" = "hour", "min" = "min", "sec" = "sec")) |>
  distinct(X, Y, location)


joint_sun <- move_sun |>
  filter(type == "check-in") |>
  inner_join(comm_sun, by = c("id" = "from", "day" = "day", "hour" = "hour", "min" = "min", "sec" = "sec")) |>
  distinct(X, Y, location)


joint_rides <- rbind(joint_fri,joint_sat,joint_sun) |>
  distinct(X, Y, location)
```


```{r}
library(ggplot2)
library(jpeg)
map_image <- readJPEG("~/Documents/RStudio/SDS 235/SDS235-HW2/hw02-data/Auxiliary Files/Park Map.jpg")
map_grid <- grid::rasterGrob(map_image, width=unit(1,"npc"), height=unit(1,"npc"))


#with map behind, doesn't align perfectly
ggplot(joint_rides, aes(as.numeric(X), as.numeric(Y), color = location))+ 
  annotation_custom(map_grid) +
  geom_point(size = 5) +
  scale_y_continuous(limits = c(5,95)) +
  scale_x_continuous(limits = c(5,95))

map <- ggplot(joint_rides, aes(as.numeric(X), as.numeric(Y), color = location))+ 
  geom_point(size = 1) +
  scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101)) +
  scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101))
```


```{r}
kiddie_poly <- data.frame(
  x = c(71, 83, 83, 101,101, 71),
  y = c(52, 52, 31, 31, 101, 101)
)

alp <- 0.15

ggplot() +
  scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101)) +
  scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101)) +
  geom_rect(mapping = aes(xmin = -1, xmax = 101, ymin = 0, ymax = 30.5), fill = "red", alpha = alp, color = "red") +
  geom_rect(mapping = aes(xmin = -1, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "deeppink", alpha = alp, color = "deeppink") +
  geom_rect(mapping = aes(xmin = -1, xmax = 55, ymin = 52, ymax = 101), fill = "blue", alpha = alp, color = "blue") +
  geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 101), fill = "yellow", alpha = alp, color = "yellow") +
  geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "green", alpha = alp, color = "green") +
  geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y), color = location), size = 1)
```



```{r}
library(ggplot2)
library(plotly)
move_fri_min <- move_fri |>
  filter(sec == "00") |>
  filter(min == "00" | min == "30") |>
  mutate(time = as.numeric(paste0(hour,".", min)))

g <- ggplot() +
  scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101)) +
  scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(-1,101)) +
  geom_rect(mapping = aes(xmin = -1, xmax = 101, ymin = 0, ymax = 30.5), fill = "red", alpha = alp, color = "red") +
  geom_rect(mapping = aes(xmin = -1, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "deeppink", alpha = alp, color = "deeppink") +
  geom_rect(mapping = aes(xmin = -1, xmax = 55, ymin = 52, ymax = 101), fill = "blue", alpha = alp, color = "blue") +
  geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 101), fill = "yellow", alpha = alp, color = "yellow") +
  geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "green", alpha = alp, color = "green") +
  geom_point(move_fri_min, mapping = aes(as.numeric(X), as.numeric(Y), color = id, frame = hour), size = 1)

ggplotly(g)


ggplotly(ggplot(move_fri_min, aes(x = X, y = Y, frame = time)) + geom_bin2d(bins = 200))

alp = 0
```



```{r}
kiddie_poly <- data.frame(
  x = c(71, 83, 83, 100,100, 71),
  y = c(52, 52, 31, 31, 100, 100)
)
ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    geom_rect(mapping = aes(xmin = 0, xmax = 100, ymin = 0, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 0, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "NA", color = "deeppink") +
    geom_rect(mapping = aes(xmin = 0, xmax = 55, ymin = 52, ymax = 100), fill = "NA", color = "blue") +
    geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 100), fill = "NA", color = "yellow") +
    geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "NA", color = "green") +
    geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = move_fri_min, mapping = aes(x = X, y = Y, frame = time), bins = 200) +
    scale_fill_viridis_c()
  )
```





# from sarah: 

```{r}
library(tidyverse)
library(plotly)
library(crosstalk)
library(lubridate)

# her method takes forever so I'm going to use mine to read in and separate the data
move_fri <- read_csv("hw02-data/Movement Data/park-movement-Fri.csv")

# split data up into desired columns 
move_fri[c("Date", "Time")] <- stringr::str_split_fixed(move_fri$Timestamp, " ", 2)
move_fri[c("Year", "Month", "Day")] <- stringr::str_split_fixed(move_fri$Date, "-", 3)
move_fri[c("Hour", "Minute", "Second")] <- stringr::str_split_fixed(move_fri$Time, ":", 3)

# drop unnecessary columns
move_fri <- move_fri |> 
  select(-c(Timestamp, Date, Time, Year, Second))
# so now we have a data frame for friday data that is just the id, coordinates, and date time broken down easily manipulate cols

# create the final df: 
pop_fri <- move_fri |> 
  group_by(Day, Hour, Minute, X, Y) |> 
  summarize(grid_pop = length(id)) |> 
  ungroup() |> 
  group_by(Hour, Minute) |> 
  mutate(total_pop = sum(grid_pop),
         datetime = paste(Hour, Minute, sep = ":")) |> 
  ungroup()

# create df filtered to only include on the hour and half hour marks
pop_fri_shared <- pop_fri |> 
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))
```


#sian new below
```{r}
library(tidyverse)
library(plotly)
library(crosstalk)
library(lubridate)
# her method takes forever so I'm going to use mine to read in and separate the data
move_fri <- read_csv("hw02-data/Movement Data/park-movement-Fri.csv")
move_sat <- read_csv("hw02-data/Movement Data/park-movement-Sat.csv")
move_sun <- read_csv("hw02-data/Movement Data/park-movement-Sun.csv")

# split data up into desired columns 
move_fri[c("Date", "Time")] <- stringr::str_split_fixed(move_fri$Timestamp, " ", 2)
move_fri[c("Year", "Month", "Day")] <- stringr::str_split_fixed(move_fri$Date, "-", 3)
move_fri[c("Hour", "Minute", "Second")] <- stringr::str_split_fixed(move_fri$Time, ":", 3)

move_sat[c("Date", "Time")] <- stringr::str_split_fixed(move_sat$Timestamp, " ", 2)
move_sat[c("Year", "Month", "Day")] <- stringr::str_split_fixed(move_sat$Date, "-", 3)
move_sat[c("Hour", "Minute", "Second")] <- stringr::str_split_fixed(move_sat$Time, ":", 3)

move_sun[c("Date", "Time")] <- stringr::str_split_fixed(move_sun$Timestamp, " ", 2)
move_sun[c("Year", "Month", "Day")] <- stringr::str_split_fixed(move_sun$Date, "-", 3)
move_sun[c("Hour", "Minute", "Second")] <- stringr::str_split_fixed(move_sun$Time, ":", 3)

# drop unnecessary columns
move_fri <- move_fri |> 
  select(-c(Timestamp, Time, Year, Second))

move_sat <- move_sat |> 
  select(-c(Timestamp, Time, Year, Second))

move_sun <- move_sun |> 
  select(-c(Timestamp, Time, Year, Second))


# so now we have a data frame for friday data that is just the id, coordinates, and date time broken down easily manipulate cols

# creates dataframe with total population by datetime
total_pop_fri <- move_fri|>
  group_by(Day, Hour, Minute) |> 
  summarize(total_pop = length(id)) |> 
  ungroup() |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))

total_pop_sat <- move_sat|>
  group_by(Day, Hour, Minute) |> 
  summarize(total_pop = length(id)) |> 
  ungroup() |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))




total_pop_sun <- move_sun|>
  group_by(Day, Hour, Minute) |> 
  summarize(total_pop = length(id)) |> 
  ungroup() |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))



#creates dataframe with each id moving by time
pop_fri <- move_fri |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))

pop_sat <- move_sat |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))

pop_sun <- move_sun |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup() |>
  filter(grepl(":00$", datetime) | grepl(":30$", datetime))

# create df filtered to only include on the hour and half hour marks
pop_fri_shared <- left_join(pop_fri, total_pop_fri, by = c("Day" = "Day", "Hour" = "Hour", "Minute" = "Minute", "datetime" = "datetime"))
pop_sat_shared <- left_join(pop_sat, total_pop_sat, by = c("Day" = "Day", "Hour" = "Hour", "Minute" = "Minute", "datetime" = "datetime"))
pop_sun_shared <- left_join(pop_sun, total_pop_sun, by = c("Day" = "Day", "Hour" = "Hour", "Minute" = "Minute", "datetime" = "datetime"))


pop_shared <- rbind(pop_fri, pop_sat, pop_sun)

pop_shared$X <- as.numeric(pop_shared$X)
pop_shared$Y <- as.numeric(pop_shared$Y)
```


```{r}
pop_fri_test <- move_fri |>
  group_by(Day, Hour) |> 
  mutate(datetime = paste(Day, Hour, sep = ", "))

pop_sat_test <- move_sat |>
  group_by(Day, Hour) |> 
  mutate(datetime = paste(Day, Hour, sep = ", "))

pop_sun_test <- move_sun |>
  group_by(Day, Hour) |> 
  mutate(datetime = paste(Day, Hour, sep = ", "))

pop_sun_test$X <- as.numeric(pop_sun_test$X)
pop_sun_test$Y <- as.numeric(pop_sun_test$Y)

pop_sat_test$X <- as.numeric(pop_sat_test$X)
pop_sat_test$Y <- as.numeric(pop_sat_test$Y)

pop_fri_test$X <- as.numeric(pop_fri_test$X)
pop_fri_test$Y <- as.numeric(pop_fri_test$Y)

pop_all_test <- cbind(pop_fri_test, pop_sat_test, pop_sun_test)


ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    geom_rect(mapping = aes(xmin = 0, xmax = 100, ymin = 0, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 0, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "NA", color = "deeppink") +
    geom_rect(mapping = aes(xmin = 0, xmax = 55, ymin = 52, ymax = 100), fill = "NA", color = "blue") +
    geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 100), fill = "NA", color = "yellow") +
    geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "NA", color = "green") +
    geom_bin2d(data = pop_sun_test, mapping = aes(x = X, y = Y, frame = Hour)) +
    scale_fill_viridis_c()
  )
```





```{r}
all_min_sun <- move_sun |> 
  group_by(Hour, Minute) |> 
  mutate(datetime = paste(Hour, Minute, sep = ":"),
         datetime = paste(Day, datetime, sep = ", ")) |>
  ungroup()

all_min_sun$X <- as.numeric(all_min_sun$X)
all_min_sun$Y <- as.numeric(all_min_sun$Y)




ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    geom_rect(mapping = aes(xmin = 0, xmax = 100, ymin = 0, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 0, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "NA", color = "deeppink") +
    geom_rect(mapping = aes(xmin = 0, xmax = 55, ymin = 52, ymax = 100), fill = "NA", color = "blue") +
    geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 100), fill = "NA", color = "yellow") +
    geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "NA", color = "green") +
    #geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = all_min_sun, mapping = aes(x = X, y = Y, frame = datetime)) +
    scale_fill_viridis_c()
  )


ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 20, to = 40, by = 5),limits = c(20,40)) +
    scale_x_continuous(breaks = seq(from = 30, to = 35, by = 5),limits = c(30,35)) +
    geom_rect(mapping = aes(xmin = 30, xmax = 35, ymin = 20, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 30, xmax = 35, ymin = 31, ymax = 40), fill = "NA", color = "deeppink") +
    geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = all_min_sun, mapping = aes(x = X, y = Y, frame = datetime), bins = 400) +
    scale_fill_viridis_c()
  )
```






```{r}
kiddie_poly <- data.frame(
  x = c(71, 83, 83, 100,100, 71),
  y = c(52, 52, 31, 31, 100, 100)
)



ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    geom_rect(mapping = aes(xmin = 0, xmax = 100, ymin = 0, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 0, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "NA", color = "deeppink") +
    geom_rect(mapping = aes(xmin = 0, xmax = 55, ymin = 52, ymax = 100), fill = "NA", color = "blue") +
    geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 100), fill = "NA", color = "yellow") +
    geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "NA", color = "green") +
    geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = pop_shared, mapping = aes(x = X, y = Y, frame = datetime)) +
    scale_fill_viridis_c() +
    scale_fill
  )



ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    scale_x_continuous(breaks = seq(from = 0, to = 100, by = 5),limits = c(0,100)) +
    geom_rect(mapping = aes(xmin = 0, xmax = 100, ymin = 0, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 0, xmax = 82.5, ymin = 31, ymax = 51.5), fill = "NA", color = "deeppink") +
    geom_rect(mapping = aes(xmin = 0, xmax = 55, ymin = 52, ymax = 100), fill = "NA", color = "blue") +
    geom_rect(mapping = aes(xmin = 55.5, xmax = 70.5, ymin = 52, ymax = 100), fill = "NA", color = "yellow") +
    geom_polygon(data = kiddie_poly, mapping = aes(x = x, y = y), fill = "NA", color = "green") +
    #geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = pop_shared, mapping = aes(x = X, y = Y, frame = datetime), bins = 40) +
    scale_fill_viridis_c()
  )


```

```{r}

ggplotly(
  ggplot() + 
    scale_y_continuous(breaks = seq(from = 5, to = 45, by = 5),limits = c(5,45)) +
    scale_x_continuous(breaks = seq(from = 25, to = 45, by = 5),limits = c(25,45)) +
    geom_rect(mapping = aes(xmin = 25, xmax = 45, ymin = 5, ymax = 30.5), fill = "NA", color = "red") +
    geom_rect(mapping = aes(xmin = 25, xmax = 45, ymin = 31, ymax = 45), fill = "NA", color = "deeppink") +
    geom_point(joint_rides, mapping = aes(as.numeric(X), as.numeric(Y))) +
    geom_bin2d(data = pop_shared, mapping = aes(x = X, y = Y, frame = datetime), bins = 10) +
    scale_fill_viridis_c()
  )
```







